// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("BattleResultsCom")));
bytes32 constant BattleResultsComponentsTableId = _tableId;

struct BattleResultsComponentsData {
  uint32 totalWins;
  uint32 totalLoses;
}

library BattleResultsComponents {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.UINT32;
    _schema[1] = SchemaType.UINT32;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](2);
    _fieldNames[0] = "totalWins";
    _fieldNames[1] = "totalLoses";
    return ("BattleResultsComponents", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get totalWins */
  function getTotalWins(bytes32 playerID) internal view returns (uint32 totalWins) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerID;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get totalWins (using the specified store) */
  function getTotalWins(IStore _store, bytes32 playerID) internal view returns (uint32 totalWins) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerID;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set totalWins */
  function setTotalWins(bytes32 playerID, uint32 totalWins) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerID;

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((totalWins)));
  }

  /** Set totalWins (using the specified store) */
  function setTotalWins(IStore _store, bytes32 playerID, uint32 totalWins) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerID;

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((totalWins)));
  }

  /** Get totalLoses */
  function getTotalLoses(bytes32 playerID) internal view returns (uint32 totalLoses) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerID;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get totalLoses (using the specified store) */
  function getTotalLoses(IStore _store, bytes32 playerID) internal view returns (uint32 totalLoses) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerID;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set totalLoses */
  function setTotalLoses(bytes32 playerID, uint32 totalLoses) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerID;

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((totalLoses)));
  }

  /** Set totalLoses (using the specified store) */
  function setTotalLoses(IStore _store, bytes32 playerID, uint32 totalLoses) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerID;

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((totalLoses)));
  }

  /** Get the full data */
  function get(bytes32 playerID) internal view returns (BattleResultsComponentsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerID;

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, bytes32 playerID) internal view returns (BattleResultsComponentsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerID;

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(bytes32 playerID, uint32 totalWins, uint32 totalLoses) internal {
    bytes memory _data = encode(totalWins, totalLoses);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerID;

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(IStore _store, bytes32 playerID, uint32 totalWins, uint32 totalLoses) internal {
    bytes memory _data = encode(totalWins, totalLoses);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerID;

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(bytes32 playerID, BattleResultsComponentsData memory _table) internal {
    set(playerID, _table.totalWins, _table.totalLoses);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, bytes32 playerID, BattleResultsComponentsData memory _table) internal {
    set(_store, playerID, _table.totalWins, _table.totalLoses);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal pure returns (BattleResultsComponentsData memory _table) {
    _table.totalWins = (uint32(Bytes.slice4(_blob, 0)));

    _table.totalLoses = (uint32(Bytes.slice4(_blob, 4)));
  }

  /** Tightly pack full data using this table's schema */
  function encode(uint32 totalWins, uint32 totalLoses) internal view returns (bytes memory) {
    return abi.encodePacked(totalWins, totalLoses);
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(bytes32 playerID) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerID;
  }

  /* Delete all data for given keys */
  function deleteRecord(bytes32 playerID) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerID;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, bytes32 playerID) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerID;

    _store.deleteRecord(_tableId, _keyTuple);
  }
}
