// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

// Import user types
import { BattleOptions } from "./../Types.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("BattlePreResults")));
bytes32 constant BattlePreResultsComponentsTableId = _tableId;

struct BattlePreResultsComponentsData {
  BattleOptions option;
  string result;
}

library BattlePreResultsComponents {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.UINT8;
    _schema[1] = SchemaType.STRING;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](2);
    _fieldNames[0] = "option";
    _fieldNames[1] = "result";
    return ("BattlePreResultsComponents", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get option */
  function getOption(bytes32 playerId) internal view returns (BattleOptions option) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return BattleOptions(uint8(Bytes.slice1(_blob, 0)));
  }

  /** Get option (using the specified store) */
  function getOption(IStore _store, bytes32 playerId) internal view returns (BattleOptions option) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return BattleOptions(uint8(Bytes.slice1(_blob, 0)));
  }

  /** Set option */
  function setOption(bytes32 playerId, BattleOptions option) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked(uint8(option)));
  }

  /** Set option (using the specified store) */
  function setOption(IStore _store, bytes32 playerId, BattleOptions option) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked(uint8(option)));
  }

  /** Get result */
  function getResult(bytes32 playerId) internal view returns (string memory result) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (string(_blob));
  }

  /** Get result (using the specified store) */
  function getResult(IStore _store, bytes32 playerId) internal view returns (string memory result) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (string(_blob));
  }

  /** Set result */
  function setResult(bytes32 playerId, string memory result) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreSwitch.setField(_tableId, _keyTuple, 1, bytes((result)));
  }

  /** Set result (using the specified store) */
  function setResult(IStore _store, bytes32 playerId, string memory result) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    _store.setField(_tableId, _keyTuple, 1, bytes((result)));
  }

  /** Get the length of result */
  function lengthResult(bytes32 playerId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    uint256 _byteLength = StoreSwitch.getFieldLength(_tableId, _keyTuple, 1, getSchema());
    return _byteLength / 1;
  }

  /** Get the length of result (using the specified store) */
  function lengthResult(IStore _store, bytes32 playerId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    uint256 _byteLength = _store.getFieldLength(_tableId, _keyTuple, 1, getSchema());
    return _byteLength / 1;
  }

  /** Get an item of result (unchecked, returns invalid data if index overflows) */
  function getItemResult(bytes32 playerId, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    bytes memory _blob = StoreSwitch.getFieldSlice(_tableId, _keyTuple, 1, getSchema(), _index * 1, (_index + 1) * 1);
    return (string(_blob));
  }

  /** Get an item of result (using the specified store) (unchecked, returns invalid data if index overflows) */
  function getItemResult(IStore _store, bytes32 playerId, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    bytes memory _blob = _store.getFieldSlice(_tableId, _keyTuple, 1, getSchema(), _index * 1, (_index + 1) * 1);
    return (string(_blob));
  }

  /** Push a slice to result */
  function pushResult(bytes32 playerId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreSwitch.pushToField(_tableId, _keyTuple, 1, bytes((_slice)));
  }

  /** Push a slice to result (using the specified store) */
  function pushResult(IStore _store, bytes32 playerId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    _store.pushToField(_tableId, _keyTuple, 1, bytes((_slice)));
  }

  /** Pop a slice from result */
  function popResult(bytes32 playerId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreSwitch.popFromField(_tableId, _keyTuple, 1, 1);
  }

  /** Pop a slice from result (using the specified store) */
  function popResult(IStore _store, bytes32 playerId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    _store.popFromField(_tableId, _keyTuple, 1, 1);
  }

  /** Update a slice of result at `_index` */
  function updateResult(bytes32 playerId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreSwitch.updateInField(_tableId, _keyTuple, 1, _index * 1, bytes((_slice)));
  }

  /** Update a slice of result (using the specified store) at `_index` */
  function updateResult(IStore _store, bytes32 playerId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    _store.updateInField(_tableId, _keyTuple, 1, _index * 1, bytes((_slice)));
  }

  /** Get the full data */
  function get(bytes32 playerId) internal view returns (BattlePreResultsComponentsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, bytes32 playerId) internal view returns (BattlePreResultsComponentsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(bytes32 playerId, BattleOptions option, string memory result) internal {
    bytes memory _data = encode(option, result);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(IStore _store, bytes32 playerId, BattleOptions option, string memory result) internal {
    bytes memory _data = encode(option, result);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(bytes32 playerId, BattlePreResultsComponentsData memory _table) internal {
    set(playerId, _table.option, _table.result);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, bytes32 playerId, BattlePreResultsComponentsData memory _table) internal {
    set(_store, playerId, _table.option, _table.result);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal view returns (BattlePreResultsComponentsData memory _table) {
    // 1 is the total byte length of static data
    PackedCounter _encodedLengths = PackedCounter.wrap(Bytes.slice32(_blob, 1));

    _table.option = BattleOptions(uint8(Bytes.slice1(_blob, 0)));

    // Store trims the blob if dynamic fields are all empty
    if (_blob.length > 1) {
      uint256 _start;
      // skip static data length + dynamic lengths word
      uint256 _end = 33;

      _start = _end;
      _end += _encodedLengths.atIndex(0);
      _table.result = (string(SliceLib.getSubslice(_blob, _start, _end).toBytes()));
    }
  }

  /** Tightly pack full data using this table's schema */
  function encode(BattleOptions option, string memory result) internal view returns (bytes memory) {
    uint40[] memory _counters = new uint40[](1);
    _counters[0] = uint40(bytes(result).length);
    PackedCounter _encodedLengths = PackedCounterLib.pack(_counters);

    return abi.encodePacked(option, _encodedLengths.unwrap(), bytes((result)));
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(bytes32 playerId) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;
  }

  /* Delete all data for given keys */
  function deleteRecord(bytes32 playerId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, bytes32 playerId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    _store.deleteRecord(_tableId, _keyTuple);
  }
}
