// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("PossibleComponen")));
bytes32 constant PossibleComponentTableId = _tableId;

struct PossibleComponentData {
  uint256 createdAt;
  uint256 actionLength;
  bytes actions;
}

library PossibleComponent {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](3);
    _schema[0] = SchemaType.UINT256;
    _schema[1] = SchemaType.UINT256;
    _schema[2] = SchemaType.BYTES;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.BYTES32;
    _schema[1] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](3);
    _fieldNames[0] = "createdAt";
    _fieldNames[1] = "actionLength";
    _fieldNames[2] = "actions";
    return ("PossibleComponent", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get createdAt */
  function getCreatedAt(
    bytes32 interactingEntityID,
    bytes32 interactedEntityID
  ) internal view returns (uint256 createdAt) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get createdAt (using the specified store) */
  function getCreatedAt(
    IStore _store,
    bytes32 interactingEntityID,
    bytes32 interactedEntityID
  ) internal view returns (uint256 createdAt) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set createdAt */
  function setCreatedAt(bytes32 interactingEntityID, bytes32 interactedEntityID, uint256 createdAt) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((createdAt)));
  }

  /** Set createdAt (using the specified store) */
  function setCreatedAt(
    IStore _store,
    bytes32 interactingEntityID,
    bytes32 interactedEntityID,
    uint256 createdAt
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((createdAt)));
  }

  /** Get actionLength */
  function getActionLength(
    bytes32 interactingEntityID,
    bytes32 interactedEntityID
  ) internal view returns (uint256 actionLength) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get actionLength (using the specified store) */
  function getActionLength(
    IStore _store,
    bytes32 interactingEntityID,
    bytes32 interactedEntityID
  ) internal view returns (uint256 actionLength) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set actionLength */
  function setActionLength(bytes32 interactingEntityID, bytes32 interactedEntityID, uint256 actionLength) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((actionLength)));
  }

  /** Set actionLength (using the specified store) */
  function setActionLength(
    IStore _store,
    bytes32 interactingEntityID,
    bytes32 interactedEntityID,
    uint256 actionLength
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((actionLength)));
  }

  /** Get actions */
  function getActions(
    bytes32 interactingEntityID,
    bytes32 interactedEntityID
  ) internal view returns (bytes memory actions) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 2);
    return (bytes(_blob));
  }

  /** Get actions (using the specified store) */
  function getActions(
    IStore _store,
    bytes32 interactingEntityID,
    bytes32 interactedEntityID
  ) internal view returns (bytes memory actions) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 2);
    return (bytes(_blob));
  }

  /** Set actions */
  function setActions(bytes32 interactingEntityID, bytes32 interactedEntityID, bytes memory actions) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    StoreSwitch.setField(_tableId, _keyTuple, 2, bytes((actions)));
  }

  /** Set actions (using the specified store) */
  function setActions(
    IStore _store,
    bytes32 interactingEntityID,
    bytes32 interactedEntityID,
    bytes memory actions
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    _store.setField(_tableId, _keyTuple, 2, bytes((actions)));
  }

  /** Get the length of actions */
  function lengthActions(bytes32 interactingEntityID, bytes32 interactedEntityID) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    uint256 _byteLength = StoreSwitch.getFieldLength(_tableId, _keyTuple, 2, getSchema());
    return _byteLength / 1;
  }

  /** Get the length of actions (using the specified store) */
  function lengthActions(
    IStore _store,
    bytes32 interactingEntityID,
    bytes32 interactedEntityID
  ) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    uint256 _byteLength = _store.getFieldLength(_tableId, _keyTuple, 2, getSchema());
    return _byteLength / 1;
  }

  /** Get an item of actions (unchecked, returns invalid data if index overflows) */
  function getItemActions(
    bytes32 interactingEntityID,
    bytes32 interactedEntityID,
    uint256 _index
  ) internal view returns (bytes memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    bytes memory _blob = StoreSwitch.getFieldSlice(_tableId, _keyTuple, 2, getSchema(), _index * 1, (_index + 1) * 1);
    return (bytes(_blob));
  }

  /** Get an item of actions (using the specified store) (unchecked, returns invalid data if index overflows) */
  function getItemActions(
    IStore _store,
    bytes32 interactingEntityID,
    bytes32 interactedEntityID,
    uint256 _index
  ) internal view returns (bytes memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    bytes memory _blob = _store.getFieldSlice(_tableId, _keyTuple, 2, getSchema(), _index * 1, (_index + 1) * 1);
    return (bytes(_blob));
  }

  /** Push a slice to actions */
  function pushActions(bytes32 interactingEntityID, bytes32 interactedEntityID, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    StoreSwitch.pushToField(_tableId, _keyTuple, 2, bytes((_slice)));
  }

  /** Push a slice to actions (using the specified store) */
  function pushActions(
    IStore _store,
    bytes32 interactingEntityID,
    bytes32 interactedEntityID,
    bytes memory _slice
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    _store.pushToField(_tableId, _keyTuple, 2, bytes((_slice)));
  }

  /** Pop a slice from actions */
  function popActions(bytes32 interactingEntityID, bytes32 interactedEntityID) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    StoreSwitch.popFromField(_tableId, _keyTuple, 2, 1);
  }

  /** Pop a slice from actions (using the specified store) */
  function popActions(IStore _store, bytes32 interactingEntityID, bytes32 interactedEntityID) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    _store.popFromField(_tableId, _keyTuple, 2, 1);
  }

  /** Update a slice of actions at `_index` */
  function updateActions(
    bytes32 interactingEntityID,
    bytes32 interactedEntityID,
    uint256 _index,
    bytes memory _slice
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    StoreSwitch.updateInField(_tableId, _keyTuple, 2, _index * 1, bytes((_slice)));
  }

  /** Update a slice of actions (using the specified store) at `_index` */
  function updateActions(
    IStore _store,
    bytes32 interactingEntityID,
    bytes32 interactedEntityID,
    uint256 _index,
    bytes memory _slice
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    _store.updateInField(_tableId, _keyTuple, 2, _index * 1, bytes((_slice)));
  }

  /** Get the full data */
  function get(
    bytes32 interactingEntityID,
    bytes32 interactedEntityID
  ) internal view returns (PossibleComponentData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(
    IStore _store,
    bytes32 interactingEntityID,
    bytes32 interactedEntityID
  ) internal view returns (PossibleComponentData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(
    bytes32 interactingEntityID,
    bytes32 interactedEntityID,
    uint256 createdAt,
    uint256 actionLength,
    bytes memory actions
  ) internal {
    bytes memory _data = encode(createdAt, actionLength, actions);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(
    IStore _store,
    bytes32 interactingEntityID,
    bytes32 interactedEntityID,
    uint256 createdAt,
    uint256 actionLength,
    bytes memory actions
  ) internal {
    bytes memory _data = encode(createdAt, actionLength, actions);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(bytes32 interactingEntityID, bytes32 interactedEntityID, PossibleComponentData memory _table) internal {
    set(interactingEntityID, interactedEntityID, _table.createdAt, _table.actionLength, _table.actions);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(
    IStore _store,
    bytes32 interactingEntityID,
    bytes32 interactedEntityID,
    PossibleComponentData memory _table
  ) internal {
    set(_store, interactingEntityID, interactedEntityID, _table.createdAt, _table.actionLength, _table.actions);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal view returns (PossibleComponentData memory _table) {
    // 64 is the total byte length of static data
    PackedCounter _encodedLengths = PackedCounter.wrap(Bytes.slice32(_blob, 64));

    _table.createdAt = (uint256(Bytes.slice32(_blob, 0)));

    _table.actionLength = (uint256(Bytes.slice32(_blob, 32)));

    // Store trims the blob if dynamic fields are all empty
    if (_blob.length > 64) {
      uint256 _start;
      // skip static data length + dynamic lengths word
      uint256 _end = 96;

      _start = _end;
      _end += _encodedLengths.atIndex(0);
      _table.actions = (bytes(SliceLib.getSubslice(_blob, _start, _end).toBytes()));
    }
  }

  /** Tightly pack full data using this table's schema */
  function encode(uint256 createdAt, uint256 actionLength, bytes memory actions) internal view returns (bytes memory) {
    uint40[] memory _counters = new uint40[](1);
    _counters[0] = uint40(bytes(actions).length);
    PackedCounter _encodedLengths = PackedCounterLib.pack(_counters);

    return abi.encodePacked(createdAt, actionLength, _encodedLengths.unwrap(), bytes((actions)));
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(
    bytes32 interactingEntityID,
    bytes32 interactedEntityID
  ) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;
  }

  /* Delete all data for given keys */
  function deleteRecord(bytes32 interactingEntityID, bytes32 interactedEntityID) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, bytes32 interactingEntityID, bytes32 interactedEntityID) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = interactingEntityID;
    _keyTuple[1] = interactedEntityID;

    _store.deleteRecord(_tableId, _keyTuple);
  }
}
