projectName: imaigine
nameSpace: dev
appType:
  frontend: webapp

replicaSet: 1

webappContainerService:
  type: ClusterIP  # {{ .Values.webappContainerService.type }}
  port: 3000       # {{ .Values.webappContainerService.port }}

domainName: imaigine.world                # {{ .Values.domainName }}


dockerImage: oostvoort/imaigine-dev:latest