#   
#   stage: deploy
#   tags:
#     - docker-node12

stages:
  - deploy

deploy_development:
  image: oostvoort/node-alpine-aws:node12
  stage: deploy
  only:
    refs:
      - dev
    changes:
      - "./**"

  before_script:
  - eval $(ssh-agent -s)
  - echo "$DEPLOY_KEY" | base64 -d | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -p 22 174.138.22.99 >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
    - rsync -arv -e 'ssh -o StrictHostKeyChecking=no -p 22' . "root"@"174.138.22.99":/root/imaigine-gameplay/
