stages:
  - staging

Deploy:
  stage: staging
  tags:
    - dev
  before_script:
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_KEY" | base64 -d | tr -d '\r' | ssh-add -
   
  script:     
    - rsync -avr -e 'ssh -p 22' --exclude=".git" --exclude=".idea" --delete . "$USER"@"$HOSTNAME":/root/imaigine-gameplay/
