
stages:
  - deploy
deploy_development:
  stage: deploy
  only:
    refs:
      - dev
  before_script:
    - apk add --update openssh-client 
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh
    - touch ~/.ssh/id.rsa
    - chmod 600 ~/.ssh/id.rsa
    - echo "$DEPLOY_KEY" | base64 -d | tr -d '\r' > ~/.ssh/id.rsa | ssh-add ~/.ssh/id.rsa
  script:
    - rsync -arv -e 'ssh -o StrictHostKeyChecking=no -p 22' . "web"@"23.106.252.144":/root/imaigine-gameplay/
