services:
  imaigine:
    image: imaigine_gameplay:0.1.0
    container_name: imaigine_gameplay_production
    ports:
      - "3000:3000"
    env_file:
      - .env.server
    healthcheck:
      test: "curl http://localhost:3000 || exit 1"
      interval: 10s
      timeout: 5s
      retries: 100
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.imaigine.loadbalancer.server.port=3000"
      - "traefik.http.routers.imaigine.rule=Host(`imaigine.world`)"
      - "traefik.http.routers.imaigine.tls.certresolver=le"
      - "traefik.http.routers.imaigine.entrypoints=websecure"

      # HTTP Entrypoint (redirects to HTTPS)
      - "traefik.http.routers.imaigine_http.rule=Host(`imaigine.world`)"
      - "traefik.http.routers.imaigine_http.entrypoints=web"
      - "traefik.http.routers.imaigine_http.middlewares=imaigine_http@docker"

      # Redirect Middleware
      - "traefik.http.middlewares.imaigine_http.redirectscheme.scheme=https"

networks:
  traefik:
    external: true
