// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { CharacterStatsComponent, CharacterStatsComponentData, CharacterStatsComponentTableId } from "./tables/CharacterStatsComponent.sol";
import { CharacterStoryComponent, CharacterStoryComponentData, CharacterStoryComponentTableId } from "./tables/CharacterStoryComponent.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
