// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { StoryComponent, StoryComponentData, StoryComponentTableId } from "./tables/StoryComponent.sol";
import { ItemComponent, ItemComponentTableId } from "./tables/ItemComponent.sol";
import { OwnerComponent, OwnerComponentTableId } from "./tables/OwnerComponent.sol";
import { AliveComponent, AliveComponentTableId } from "./tables/AliveComponent.sol";
import { NameComponent, NameComponentTableId } from "./tables/NameComponent.sol";
import { SummaryComponent, SummaryComponentTableId } from "./tables/SummaryComponent.sol";
import { ImageComponent, ImageComponentTableId } from "./tables/ImageComponent.sol";
import { PriceComponent, PriceComponentTableId } from "./tables/PriceComponent.sol";
import { RaceComponent, RaceComponentTableId } from "./tables/RaceComponent.sol";
import { CharacterComponent, CharacterComponentTableId } from "./tables/CharacterComponent.sol";
import { TangibleComponent, TangibleComponentTableId } from "./tables/TangibleComponent.sol";
import { CountComponent, CountComponentTableId } from "./tables/CountComponent.sol";
import { PlayerComponent, PlayerComponentTableId } from "./tables/PlayerComponent.sol";
import { LocationComponent, LocationComponentTableId } from "./tables/LocationComponent.sol";
import { SceneComponent, SceneComponentTableId } from "./tables/SceneComponent.sol";
import { PathComponent, PathComponentTableId } from "./tables/PathComponent.sol";
import { PathLocationComponent, PathLocationComponentData, PathLocationComponentTableId } from "./tables/PathLocationComponent.sol";
import { InteractComponent, InteractComponentData, InteractComponentTableId } from "./tables/InteractComponent.sol";
import { InteractionComponent, InteractionComponentData, InteractionComponentTableId } from "./tables/InteractionComponent.sol";
import { LogComponent, LogComponentTableId } from "./tables/LogComponent.sol";
import { ActionsComponent, ActionsComponentData, ActionsComponentTableId } from "./tables/ActionsComponent.sol";
import { AttributeUintComponent, AttributeUintComponentTableId } from "./tables/AttributeUintComponent.sol";
import { AttributeStringComponent, AttributeStringComponentTableId } from "./tables/AttributeStringComponent.sol";
import { StoryActionComponent, StoryActionComponentTableId } from "./tables/StoryActionComponent.sol";
