// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum InteractionType {
  NOT_INTERACTABLE,
  SINGLE,
  MULTIPLE
}

enum TravelStatus {
  NOT_TRAVELLING,
  PREPARING,
  READY_TO_TRAVEL,
  TRAVELLING
}
