// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAttributeSystem {
  function setAttributesUint(bytes32 entityID, string[] memory names, uint256[] memory values) external;
}
