// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IBackpackSystem {
  function dropItem(bytes32 itemID) external returns (bytes32);

  function pickItem(bytes32 itemID) external returns (bytes32);

  function consumeItem(bytes32 itemID) external returns (bytes32);
}
