// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { CharacterStoryComponentData, CharacterStatsComponentData } from "./../Tables.sol";

interface IGameSystem {
  function createPlayerCharacter(
    CharacterStoryComponentData memory story,
    CharacterStatsComponentData memory stats
  ) external;
}
