// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IInteractionSystem {
  function enterInteraction(bytes32 entityID) external returns (bytes32);

  function saveInteraction(
    bytes32 entityID,
    uint256 actionIndex,
    string memory logHash,
    bytes32[] memory participants,
    uint256[] memory participantsActionsLength,
    bytes[] memory participantsActions
  ) external returns (bytes32);

  function leaveInteraction(bytes32 entityID, bytes32 otherPlayerID) external returns (bytes32);

  function setEntityInitialActions(bytes32 entityID, string[] memory initialActions) external returns (bytes32);
}
