// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IInteractionSystem {
  function changeKarmaPoints(address forPlayer, int8 karmaPoints) external returns (bytes32);

  function changeKarmaPoints(bytes32 playerID, int8 karmaPoints) external returns (bytes32);

  function enterVote(bytes32 npcId) external returns (bytes32);

  function vote(bytes32 npcId, uint8 choice) external returns (bytes32);

  function move_to_close_vote(bytes32 npcId) external returns (bytes32);

  function exit_vote(bytes32 npcId, uint8 choice) external returns (bytes32);

  function open_voting(bytes32 npcId, int8 karmaPoints) external returns (bytes32);
}
