// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IInteractionSystem {
  function interactSingle(bytes32 interactableId, uint256 choiceId) external returns (bytes32);

  function interactMulti(bytes32 interactableId, uint256 choiceId) external returns (uint256);

  function openInteraction(bytes32 playerId, bytes32 interactableId) external;

  function getPlayerChoiceInSingleInteraction(bytes32 playerId) external view returns (uint256);

  function winningChoice(bytes32 interactableId) external view returns (uint256);
}
