// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ILocationSystem {
  function setLocation(bytes32 entityID, string calldata location) external;
}
