// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMinigameSystem {
  function play() external returns (bytes32);

  function leave() external returns (bytes32);
}
