// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { BattleOptions } from "./../Types.sol";

interface IMinigameSystem {
  function setUpPlayer(bytes32 playerId, bytes32 locationId) external;

  function play() external;

  function onSelect(bytes32 hash) external;

  function reveal(BattleOptions selection, string memory salt) external;

  function encodeHash(BattleOptions selection, string memory salt) external pure returns (bytes32);

  function validateBattle() external;

  function removeBattleLogs(uint256[] memory battleHistoryIds) external;

  function rematch() external;

  function leave() external;
}
