// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { BattleComponentData } from "./../Tables.sol";

interface IMinigameSystem {
  function play() external returns (bytes32);

  function setQueue(bytes32 playerId, bytes32 locationId) external returns (bytes32);

  function setMatch(
    bytes32 playerId,
    bytes32 locationId,
    bytes32 opponentId
  ) external returns (BattleComponentData memory);

  function setBetting(
    bytes32 playerId,
    bytes32 locationId,
    bytes32 hashOption
  ) external returns (BattleComponentData memory);

  function lockInBetting(bytes32 playerId, bytes32 locationId, string[] memory _hashsalt) external;
}
