// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IStorySystem {
  function setPlayerStory(bytes32 playerID, bytes32[] memory actionIDs, bytes[] memory actions) external;
}
