// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITravelSystem {
  function prepareTravel(uint256 destination) external returns (bytes32);

  function startTravel(bytes32 playerId, uint256[] memory pathCells, uint256[] memory toRevealAtDestination) external;

  function travel() external returns (uint256);
}
