export const PLAYER_IMAGE_CHOICES = 3
export const MOCK_LOCATION_IDS = [
    {"0x01": "Mystic Grove"},
    {"0x02": "Whispering Caverns"},
    {"0x03": "Serenity Lake"},
    {"0x04": "Enchanted Ruins"},
    {"0x05": "Celestial Summit"},
    {"0x06": "Shadowvale Forest"},
    {"0x07": "Crystal Falls"},
    {"0x08": "Eternal Springs"},
    {"0x09": "Windsong Meadow"},
    {"0x0A": "Starlight Citadel"},
    {"0x0B": "Goblin Market"},
    {"0x0C": "Silent Watchtower"},
    {"0x0D": "Moonlit Shores"},
    {"0x0E": "Frostfire Peaks"},
    {"0x0F": "Golden Fields"},
    {"0x10": "Thunderclap Gorge"},
    {"0x11": "Duskwraith Keep"},
    {"0x12": "Twilight Hollow"},
    {"0x13": "Crimson Valley"},
    {"0x14": "Stormhaven"},
    {"0x15": "Misthaven"},
    {"0x16": "Silverleaf Glade"},
    {"0x17": "Abyssal Abyss"},
    {"0x18": "Whirlwind Plateau"},
    {"0x19": "Coral Cove"},
    {"0x1A": "Firefly Marsh"},
    {"0x1B": "Lost Citadel"},
    {"0x1C": "Emerald Isle"},
    {"0x1D": "Ironhold Fortress"},
    {"0x1E": "Sunset Peak"},
    {"0x1F": "Dewdrop Sanctuary"},
    {"0x20": "Twinkling Treetops"}
]